server:
  port: 8181
spring:
  application:
    name: location
  main:
    show_banner: false
  profiles:
    active: production
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy